name: Daily Free Games Notifier

on:
  schedule:
    - cron: "0 20 * * *"  # JST 05:00
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # ← これが重要

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python free_distribution.py

      - name: Commit cache
        run: |
          git config --local user.email "github-actions@example.com"
          git config --local user.name "GitHub Actions"
          git pull --rebase
          git add cache.json
          git commit -m "update cache" || echo "No changes"
          git push
