name: Steam & Epic Free Notifier

on:
  schedule:
    - cron: "0 20 * * *"  # JST 05:00
  workflow_dispatch:

permissions:
  contents: write

jobs:
  notifier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
         fetch-depth: 0  # 必ず full clone
         persist-credentials: true

      - name: Configure Git
        run: |
         git config --local user.email "github-actions@example.com"
         git config --local user.name "GitHub Actions"

      # ★ リモートの最新状態を強制取得（ローカルの untracked を消す）
      - name: Reset to latest
        run: |
         git fetch origin main
         git reset --hard origin/main

      - name: Run script
        run: python free_distribution.py
        env:
         DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Commit changes
        run: |
         git add cache_steam_epic.json
         git commit -m "update cache" || echo "No changes"

      - name: Push changes
        run: |
         git push origin main
